services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"  # Expose MongoDB port
    volumes:
      - mongodb_data:/data/db  # Persistent data storage for MongoDB

  app:
    build:
      context: .  # Path to the directory containing the Dockerfile
    ports:
      - "3000:3000"  # Expose the application port
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=${MONGO_URI}   # MongoDB connection URI from environment variable
      - SECRET_KEY=${SECRET_KEY} # Secret Key

volumes:
  mongodb_data:
